### ISSUE TITLE
I keep getting an error.

### ISSUE THREAD

**Issue by koolkt** [capaj/systemjs-hot-reloader#42]
Uncaught (in promise) Error: Super expression must either be null or a function, not object
	Error loading http://localhost:9080/jspm_packages/github/capaj/systemjs-hot-reloader@0.5.1.js
    at exports.default (http://localhost:9080/jspm_packages/npm/babel-runtime@5.8.34/helpers/inherits.js:7:11)
    at http://localhost:9080/jspm_packages/github/capaj/systemjs-hot-reloader@0.5.1/hot-reloader.js!transpiled:35:9
    at execute (http://localhost:9080/jspm_packages/github/capaj/systemjs-hot-reloader@0.5.1/hot-reloader.js!transpiled:271:9)
    at u (http://localhost:9080/jspm_packages/system.js:5:2854)
    at u (http://localhost:9080/jspm_packages/system.js:5:2789)
    at Object.execute (http://localhost:9080/jspm_packages/system.js:5:5854)
    at y (http://localhost:9080/jspm_packages/system.js:4:10168)
    at x (http://localhost:9080/jspm_packages/system.js:4:10547)
    at p (http://localhost:9080/jspm_packages/system.js:4:8425)
    at h (http://localhost:9080/jspm_packages/system.js:4:8810)

**Comment by peteruithoven** [comment]
@koolkt Looks like it can't find the `systemjs-hot-reloader` file, please check your` jspm_packages` folder, whether you installed it correctly.

**Comment by koolkt** [comment]
For some reason changing: 
```  class HotReloader extends Emitter  ```
to
```  class HotReloader extends Emitter.default ```
at line 11 in hot-reloader.js solves the problem.
I don't understand how javascript export default works but it seems to be exporting Emitter as an object and the inheritance expects the default function.

**Comment by koolkt** [comment]
It might be related to this https://phabricator.babeljs.io/T2694.

**Comment by capaj** [comment]
interesting. SystemJS should resolve the default export into the Emitter.
@koolkt which version of JSPM do you have?

**Comment by Shrulik** [comment]
I experienced the same problem yesterday, and I was running on jspm@0.16.22

**Comment by koolkt** [comment]
My jspm version is 0.16.22.

**Comment by coreylenertz** [comment]
Trying hot reloading with jspm and pretty excited to see it work. Unfortunately, I'm having the same problem with jspm 0.16.23

I agree that exporting the Emitter class as default should suffice. My guess is that there is something awry in the compilation process.

**Comment by capaj** [comment]
@coreylenertz seems like this is affecting a lot of you. @guybedford is it possible, that latest systemJS is exporting it wrongly?

**Comment by bigfish** [comment]
me too.

Uncaught (in promise) Error: Super expression must either be null or a function, not object
	Error loading http://localhost:3000/jspm_packages/github/capaj/systemjs-hot-reloader@0.5.1.js
    at exports.default (http://localhost:3000/jspm_packages/npm/babel-runtime@5.8.34/helpers/inherits.js:7:11)
    at http://localhost:3000/jspm_packages/github/capaj/systemjs-hot-reloader@0.5.1/hot-reloader.js!transpiled:35:9
    at execute (http://localhost:3000/jspm_packages/github/capaj/systemjs-hot-reloader@0.5.1/hot-reloader.js!transpiled:271:9)
    at u (http://localhost:3000/jspm_packages/system.js:5:2888)
    at u (http://localhost:3000/jspm_packages/system.js:5:2823)
    at Object.execute (http://localhost:3000/jspm_packages/system.js:5:5888)
    at y (http://localhost:3000/jspm_packages/system.js:4:10168)
    at x (http://localhost:3000/jspm_packages/system.js:4:10547)
    at p (http://localhost:3000/jspm_packages/system.js:4:8425)
    at h (http://localhost:3000/jspm_packages/system.js:4:8810)

**Comment by frankwallis** [comment]
So it seems that this error is caused by the ```weakee``` package being incorrectly installed as a ```commonjs``` module when it should be ```esm```. The workaround is to add an override in your package.json:

```
    "overrides": {
      "npm:weakee@0.9.1": {
        "format": "esm"
      }
    }
```

The problem is in weakee@0.9.1.js
```
module.exports = require("npm:weakee@0.9.1/weakee.js");
```
should look like
```
export * from "npm:weakee@0.9.1/weakee.js";
export {default} from "npm:weakee@0.9.1/weakee.js";
```

@guybedford - is this a bug or does there just need to be a registry entry created for weakee?

**Comment by frankwallis** [comment]
@capaj I see ```weakee``` is your package too - you may just want to set the format in the ```jspm``` section of ```weakee/package.json```:

```
"jspm": {
  "format": "esm"
}
```

**Comment by capaj** [comment]
@frankwallis thanks, I thought this: https://github.com/capaj/weakee/blob/master/weakee.js#L1

would suffice. That should be enough to mark the script as es6. @guybedford am I not right?

**Comment by guybedford** [comment]
It seems this was due to https://github.com/jspm/jspm-cli/commit/52fe78d2a3f2faec949181b4a16ef9a9430a0567. This would work fine in jspm 0.17 though, although the package.json format is recommended over syntax.

**Comment by capaj** [comment]
@guybedford thanks for confirming. I added the format to package.json in the latest release.
Could you try it out @koolkt @Shrulik or @bigfish ?

**Comment by capaj** [comment]
reported as fixed by other users

**Comment by unional** [comment]
@capaj @guybedford , sorry to see my PR creates an issue for you.

@guybedford , do you want any improvement on this? i.e. letting the local `"format x"` overrides `package.json` setting.

**Comment by unional** [comment]
Actually, taking it partially back.  Since there was no `pjson.format` before https://github.com/capaj/weakee/commit/ba74534f5d6f6ea1974992c562b60d3332baacc4, that PR should not affect the behavior.

**Comment by jonahlau** [comment]
I am still getting this error. I've tried v0.5.5 of the hot-reloader package with jspm v0.17.0 and 0.16.24

I'm only able to get it running with hot-reloader 0.5.5 with jspm 0.16.19.
